import prisma from "../lib/prisma";

// Import enums from Prisma client
import { TimePreference, ExperienceLevel, GymFrequency } from "@prisma/client";

const dummyUsers = [
  {
    name: "Aarav Sharma",
    email: "aarav@example.com",
    passwordHash: "hashed_password_1",
    age: 24,
    heightCm: 175,
    weightKg: 70,
    location: "Toronto",
    timePreference: TimePreference.EVENING,
    experienceLevel: ExperienceLevel.INTERMEDIATE,
    gymFrequency: GymFrequency.REGULARLY,
  },
  {
    name: "Maya Patel",
    email: "maya@example.com",
    passwordHash: "hashed_password_2",
    age: 22,
    heightCm: 162,
    weightKg: 56,
    location: "Toronto",
    timePreference: TimePreference.MORNING,
    experienceLevel: ExperienceLevel.BEGINNER,
    gymFrequency: GymFrequency.OCCASIONALLY,
  },
  {
    name: "Liam Chen",
    email: "liam@example.com",
    passwordHash: "hashed_password_3",
    age: 27,
    heightCm: 180,
    weightKg: 75,
    location: "Vancouver",
    timePreference: TimePreference.EVENING,
    experienceLevel: ExperienceLevel.ADVANCED,
    gymFrequency: GymFrequency.FREQUENTLY,
  },
  {
    name: "Zara Ahmed",
    email: "zara@example.com",
    passwordHash: "hashed_password_4",
    age: 25,
    heightCm: 168,
    weightKg: 60,
    location: "Toronto",
    timePreference: TimePreference.AFTERNOON,
    experienceLevel: ExperienceLevel.INTERMEDIATE,
    gymFrequency: GymFrequency.REGULARLY,
  },
  {
    name: "Noah Singh",
    email: "noah@example.com",
    passwordHash: "hashed_password_5",
    age: 23,
    heightCm: 172,
    weightKg: 68,
    location: "Montreal",
    timePreference: TimePreference.EVENING,
    experienceLevel: ExperienceLevel.INTERMEDIATE,
    gymFrequency: GymFrequency.DAILY,
  },
  {
    name: "Sofia Kim",
    email: "sofia@example.com",
    passwordHash: "hashed_password_6",
    age: 28,
    heightCm: 158,
    weightKg: 54,
    location: "Vancouver",
    timePreference: TimePreference.MORNING,
    experienceLevel: ExperienceLevel.BEGINNER,
    gymFrequency: GymFrequency.RARELY,
  },
  {
    name: "Ethan Wong",
    email: "ethan@example.com",
    passwordHash: "hashed_password_7",
    age: 26,
    heightCm: 185,
    weightKg: 78,
    location: "Toronto",
    timePreference: TimePreference.NIGHT,
    experienceLevel: ExperienceLevel.ATHLETE,
    gymFrequency: GymFrequency.FREQUENTLY,
  },
  {
    name: "Anaya Desai",
    email: "anaya@example.com",
    passwordHash: "hashed_password_8",
    age: 24,
    heightCm: 165,
    weightKg: 59,
    location: "Calgary",
    timePreference: TimePreference.EVENING,
    experienceLevel: ExperienceLevel.INTERMEDIATE,
    gymFrequency: GymFrequency.OCCASIONALLY,
  },
  {
    name: "Jayden Roy",
    email: "jayden@example.com",
    passwordHash: "hashed_password_9",
    age: 29,
    heightCm: 178,
    weightKg: 72,
    location: "Toronto",
    timePreference: TimePreference.EVENING,
    experienceLevel: ExperienceLevel.COACH,
    gymFrequency: GymFrequency.DAILY,
  },
  {
    name: "Riya Mehta",
    email: "riya@example.com",
    passwordHash: "hashed_password_10",
    age: 21,
    heightCm: 160,
    weightKg: 52,
    location: "Montreal",
    timePreference: TimePreference.AFTERNOON,
    experienceLevel: ExperienceLevel.BEGINNER,
    gymFrequency: GymFrequency.RARELY,
  },
  {
    name: "Cynthia Marshall",
    email: "cynthia.marshall@example.com",
    passwordHash: "hashed_password_11",
    age: 28,
    heightCm: 178,
    weightKg: 82,
    location: "Vancouver",
    timePreference: TimePreference.NIGHT,
    experienceLevel: ExperienceLevel.INTERMEDIATE,
    gymFrequency: GymFrequency.OCCASIONALLY,
  },
  {
    name: "Richard Jones",
    email: "richard.jones@example.com",
    passwordHash: "hashed_password_12",
    age: 30,
    heightCm: 189,
    weightKg: 74,
    location: "Montreal",
    timePreference: TimePreference.AFTERNOON,
    experienceLevel: ExperienceLevel.COACH,
    gymFrequency: GymFrequency.FREQUENTLY,
  },
  {
    name: "Amanda Gray",
    email: "amanda.gray@example.com",
    passwordHash: "hashed_password_13",
    age: 31,
    heightCm: 164,
    weightKg: 74,
    location: "Montreal",
    timePreference: TimePreference.NIGHT,
    experienceLevel: ExperienceLevel.ATHLETE,
    gymFrequency: GymFrequency.FREQUENTLY,
  },
  {
    name: "Anthony Torres",
    email: "anthony.torres@example.com",
    passwordHash: "hashed_password_14",
    age: 32,
    heightCm: 156,
    weightKg: 59,
    location: "Toronto",
    timePreference: TimePreference.AFTERNOON,
    experienceLevel: ExperienceLevel.ADVANCED,
    gymFrequency: GymFrequency.DAILY,
  },
  {
    name: "Mitchell Wright",
    email: "mitchell.wright@example.com",
    passwordHash: "hashed_password_15",
    age: 22,
    heightCm: 172,
    weightKg: 57,
    location: "Toronto",
    timePreference: TimePreference.EVENING,
    experienceLevel: ExperienceLevel.ATHLETE,
    gymFrequency: GymFrequency.RARELY,
  },
  {
    name: "Kevin Pearson",
    email: "kevin.pearson@example.com",
    passwordHash: "hashed_password_16",
    age: 22,
    heightCm: 161,
    weightKg: 51,
    location: "Toronto",
    timePreference: TimePreference.MORNING,
    experienceLevel: ExperienceLevel.ADVANCED,
    gymFrequency: GymFrequency.FREQUENTLY,
  },
  {
    name: "Julia Jimenez",
    email: "julia.jimenez@example.com",
    passwordHash: "hashed_password_17",
    age: 27,
    heightCm: 155,
    weightKg: 74,
    location: "Montreal",
    timePreference: TimePreference.EVENING,
    experienceLevel: ExperienceLevel.COACH,
    gymFrequency: GymFrequency.RARELY,
  },
  {
    name: "Melissa Peterson",
    email: "melissa.peterson@example.com",
    passwordHash: "hashed_password_18",
    age: 24,
    heightCm: 168,
    weightKg: 77,
    location: "Vancouver",
    timePreference: TimePreference.MORNING,
    experienceLevel: ExperienceLevel.ATHLETE,
    gymFrequency: GymFrequency.RARELY,
  },
  {
    name: "Christopher Hunt",
    email: "christopher.hunt@example.com",
    passwordHash: "hashed_password_19",
    age: 29,
    heightCm: 171,
    weightKg: 75,
    location: "Ottawa",
    timePreference: TimePreference.EVENING,
    experienceLevel: ExperienceLevel.ATHLETE,
    gymFrequency: GymFrequency.NEVER,
  },
  {
    name: "Javier Stevenson",
    email: "javier.stevenson@example.com",
    passwordHash: "hashed_password_20",
    age: 21,
    heightCm: 165,
    weightKg: 72,
    location: "Ottawa",
    timePreference: TimePreference.NIGHT,
    experienceLevel: ExperienceLevel.INTERMEDIATE,
    gymFrequency: GymFrequency.OCCASIONALLY,
  },
  {
    name: "William Miller",
    email: "william.miller@example.com",
    passwordHash: "hashed_password_21",
    age: 23,
    heightCm: 185,
    weightKg: 50,
    location: "Montreal",
    timePreference: TimePreference.AFTERNOON,
    experienceLevel: ExperienceLevel.ATHLETE,
    gymFrequency: GymFrequency.RARELY,
  },
  {
    name: "Charles Smith",
    email: "charles.smith@example.com",
    passwordHash: "hashed_password_22",
    age: 28,
    heightCm: 187,
    weightKg: 59,
    location: "Toronto",
    timePreference: TimePreference.MORNING,
    experienceLevel: ExperienceLevel.COACH,
    gymFrequency: GymFrequency.FREQUENTLY,
  },
  {
    name: "Stephen Stewart",
    email: "stephen.stewart@example.com",
    passwordHash: "hashed_password_23",
    age: 24,
    heightCm: 168,
    weightKg: 64,
    location: "Montreal",
    timePreference: TimePreference.AFTERNOON,
    experienceLevel: ExperienceLevel.BEGINNER,
    gymFrequency: GymFrequency.REGULARLY,
  },
  {
    name: "Austin Moore",
    email: "austin.moore@example.com",
    passwordHash: "hashed_password_24",
    age: 30,
    heightCm: 189,
    weightKg: 56,
    location: "Montreal",
    timePreference: TimePreference.EVENING,
    experienceLevel: ExperienceLevel.BEGINNER,
    gymFrequency: GymFrequency.RARELY,
  },
  {
    name: "Crystal Bowman",
    email: "crystal.bowman@example.com",
    passwordHash: "hashed_password_25",
    age: 29,
    heightCm: 170,
    weightKg: 69,
    location: "Ottawa",
    timePreference: TimePreference.EVENING,
    experienceLevel: ExperienceLevel.ATHLETE,
    gymFrequency: GymFrequency.NEVER,
  },
  {
    name: "Charles Mercer",
    email: "charles.mercer@example.com",
    passwordHash: "hashed_password_26",
    age: 23,
    heightCm: 185,
    weightKg: 61,
    location: "Calgary",
    timePreference: TimePreference.EVENING,
    experienceLevel: ExperienceLevel.ATHLETE,
    gymFrequency: GymFrequency.OCCASIONALLY,
  },
  {
    name: "Shawn Hernandez",
    email: "shawn.hernandez@example.com",
    passwordHash: "hashed_password_27",
    age: 23,
    heightCm: 179,
    weightKg: 51,
    location: "Vancouver",
    timePreference: TimePreference.MORNING,
    experienceLevel: ExperienceLevel.ADVANCED,
    gymFrequency: GymFrequency.NEVER,
  },
  {
    name: "Brandi Andrews",
    email: "brandi.andrews@example.com",
    passwordHash: "hashed_password_28",
    age: 25,
    heightCm: 160,
    weightKg: 53,
    location: "Vancouver",
    timePreference: TimePreference.EVENING,
    experienceLevel: ExperienceLevel.COACH,
    gymFrequency: GymFrequency.NEVER,
  },
  {
    name: "Kim Walker",
    email: "kim.walker@example.com",
    passwordHash: "hashed_password_29",
    age: 25,
    heightCm: 176,
    weightKg: 83,
    location: "Vancouver",
    timePreference: TimePreference.NIGHT,
    experienceLevel: ExperienceLevel.ADVANCED,
    gymFrequency: GymFrequency.OCCASIONALLY,
  },
  {
    name: "Michelle Fleming",
    email: "michelle.fleming@example.com",
    passwordHash: "hashed_password_30",
    age: 28,
    heightCm: 171,
    weightKg: 62,
    location: "Calgary",
    timePreference: TimePreference.AFTERNOON,
    experienceLevel: ExperienceLevel.ADVANCED,
    gymFrequency: GymFrequency.NEVER,
  },
  {
    name: "Yash Barve",
    email: "yash.barve@example.com",
    passwordHash: "hashed_password_11",
    age: 28,
    heightCm: 171,
    weightKg: 62,
    location: "Waterloo",
    timePreference: TimePreference.NIGHT,
    experienceLevel: ExperienceLevel.INTERMEDIATE,
    gymFrequency: GymFrequency.OCCASIONALLY,
  },
  {
    name: "Aryaman Arora",
    email: "aryaman.arora@example.com",
    passwordHash: "hashed_password_10",
    age: 28,
    heightCm: 171,
    weightKg: 62,
    location: "Waterloo",
    timePreference: TimePreference.MORNING,
    experienceLevel: ExperienceLevel.ADVANCED,
    gymFrequency: GymFrequency.FREQUENTLY,
  },
  {
    name: "Nicholas Rebello",
    email: "nicholas.rebello@example.com",
    passwordHash: "hashed_password_30",
    age: 28,
    heightCm: 171,
    weightKg: 62,
    location: "Waterloo",
    timePreference: TimePreference.AFTERNOON,
    experienceLevel: ExperienceLevel.ADVANCED,
    gymFrequency: GymFrequency.FREQUENTLY,
  },
  {
    name: "Riyan Sunesara",
    email: "riyan.sunesara@example.com",
    passwordHash: "hashed_password_30",
    age: 28,
    heightCm: 171,
    weightKg: 62,
    location: "Waterloo",
    timePreference: TimePreference.AFTERNOON,
    experienceLevel: ExperienceLevel.ADVANCED,
    gymFrequency: GymFrequency.NEVER,
  },
  {
    name: "Grace Feng",
    email: "grace.feng@example.com",
    passwordHash: "hashed_password_30",
    age: 28,
    heightCm: 171,
    weightKg: 62,
    location: "Waterloo",
    timePreference: TimePreference.AFTERNOON,
    experienceLevel: ExperienceLevel.ADVANCED,
    gymFrequency: GymFrequency.NEVER,
  },
  {
    name: "Lucy Li",
    email: "lucy.li@example.com",
    passwordHash: "hashed_password_30",
    age: 28,
    heightCm: 171,
    weightKg: 62,
    location: "Waterloo",
    timePreference: TimePreference.AFTERNOON,
    experienceLevel: ExperienceLevel.ADVANCED,
    gymFrequency: GymFrequency.NEVER,
  },
  {
    name: "Moni Bro",
    email: "moni.bro@example.com",
    passwordHash: "hashed_password_30",
    age: 28,
    heightCm: 171,
    weightKg: 62,
    location: "Waterloo",
    timePreference: TimePreference.NONE,
    experienceLevel: ExperienceLevel.BEGINNER,
    gymFrequency: GymFrequency.NEVER,
  },
];

async function main() {
  await prisma.user.createMany({
    data: dummyUsers,
  });
}

main()
  .then(() => {
    console.log("✅ Dummy users added successfully.");
    process.exit(0);
  })
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
